### ISSUE TITLE
Opening AS3 class in editor throws exception - Error #3218

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/moonshine-feathersui-text-editor#14]
In a quite big Apache Royale project for one of my client I'm getting `Error #3218` - Unfortunately there is no more information in console to report. 
Next when I try to type - every attempt of typing text end up with `Error #3218` in console and small freeze of editor - it almost unusable. 

I'm opening this issue to start discussion what should I do in order to be able send you more information about this kind of problems - which repeats for me quite often in this project. 

OS: **Windows 10**
Moonshine: **3.3.3 build 991**

**Comment by rat-moonshine** [comment]
> @rat-moonshine Do you think we could add the verbose-stacktraces compiler option for Moonshine?

This seems to be already added during compilation in Ant build script - https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/build/build-lib.xml#L1069.

Do we need any other change or addition to support this (?) If require this feature then we needs to have this be added, in my opinion.

**Comment by joshtynjala** [comment]
@rat-moonshine You're right. It's there. It's strange that we're getting uncaught errors without the full stack trace. I'll try to figure out if there's something else we need to do.

**Comment by rat-moonshine** [comment]
Here are some related discussion on StackOverflow - https://stackoverflow.com/questions/149073/stacktrace-in-flash-actionscript-3-0. 

From the last comment it appears that the SWF needs to be compiled with `debug=true` to avail the feature:

> The getStackTrace method returns the stack trace only on the debug flash player (https://www.adobe.com/support/flashplayer/debug_downloads.html), on the release player returns null. Make sure you have the debug player installed and running.

I take a quick look in the [Ant build script](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/build/build-lib.xml#L1044) and I confirm we're building this with `debug=true`:

```
build	17-May-2022 08:59:57	CompileSWFOSX:
build	17-May-2022 08:59:57	     [echo] Compiling SWF OSX (Debug: true)
build	17-May-2022 08:59:57	     [copy] Copying 132 files to /Users/-censored-/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/assets
build	17-May-2022 08:59:58	    [mxmlc] Loading configuration file /Users/-censored-/Flex_4.16.1_AIR_33.1/frameworks/air-config.xml
```
(above output is from Bamboo build which confirms the `isDebug` value is _true_)

**Comment by joshtynjala** [comment]
I just did some initial testing in a simple AIR project, and it appears that we should be getting a full stack trace (but maybe excluding line numbers) in a release build, even without using `verbose-stacktraces`. I guess that it's possible that these exceptions are being thrown from some background process in the runtime. I'll see if I can make the same thing happen in Moonshine instead of a test project. Maybe there's something Moonshine does that I'm missing.

**Comment by joshtynjala** [comment]
Okay, so I made a Moonshine release build locally, and full stack traces for uncaught exceptions seem to be working correctly. My conclusion is that exceptions that don't have stack traces are thrown by the runtime while it is doing something in the background. There is no stack trace because the exception doesn't originate from an ActionScript function. You get the message only. In those cases, there's probably an event like `IOErrorEvent.IO_ERROR` that we might be able to use to get more info.

**Comment by piotrzarzycki21** [comment]
> Okay, so I made a Moonshine release build locally, and full stack traces for uncaught exceptions seem to be working correctly. My conclusion is that exceptions that don't have stack traces are thrown by the runtime while it is doing something in the background. There is no stack trace because the exception doesn't originate from an ActionScript function. You get the message only. In those cases, there's probably an event like `IOErrorEvent.IO_ERROR` that we might be able to use to get more info.

Josh do we need to implement something now to get that info ? Error makes editor right now to me unusable - when it happen I have two options: I can switch with writing code to Notepad or restart IDE - which is pain cause language server for that project is starting around 2 min. I would like to get to the bottom of that error and get it fixed - It's been too long since I'm struggling with it.

**Comment by joshtynjala** [comment]
There are a couple of things that we could try, but you will need to run Moonshine in a local debugger, rather than using the nightly release build.

1) Increase the memory used by the language server. As you said, you're working on a large project, so it might be causing the JVM to run out of memory.

In _ActionScriptLanguageServerManager.as_, in the `startNativeProcess()` method, you can try adding an extra argument in the the `languageServerCommand` variable.

Before:

```as3
var languageServerCommand:Vector.<String> = new <String>[
	cmdFile.nativePath,
	"-Dfile.encoding=UTF8",
	"-Droyalelib=" + frameworksPath,
	"-cp",
	cp,
	"moonshine.Main"
];
```

After:

```as3
var languageServerCommand:Vector.<String> = new <String>[
	cmdFile.nativePath,
	"-Xmx2g",
	"-Dfile.encoding=UTF8",
	"-Droyalelib=" + frameworksPath,
	"-cp",
	cp,
	"moonshine.Main"
];
```

As I understand it, the `2g` part of `-Xmx2g` means 2 GB of RAM. You could try increasing it higher, if 2g doesn't work. I don't know for sure if it's an out of memory issue, though, so there's no guarantee that this will help.

If it works, we can add a new setting to Moonshine to increase the memory used by the language server(s).

2) In the same file, in the `initializeLanguageServer()` method, set `debugMode` to `true`, which will print the messages between Moonshine and the language server to the debug console. Once the error starts happening, there might be a clue in that output. You can copy/paste it here and I'll take a look.

**Comment by piotrzarzycki21** [comment]
> There are a couple of things that we could try, but you will need to run Moonshine in a local debugger, rather than using the nightly release build.
> 
> 1. Increase the memory used by the language server. As you said, you're working on a large project, so it might be causing the JVM to run out of memory.
> 
> In _ActionScriptLanguageServerManager.as_, in the `startNativeProcess()` method, you can try adding an extra argument in the the `languageServerCommand` variable.
> 
> Before:
> 
> ```actionscript-3
> var languageServerCommand:Vector.<String> = new <String>[
> 	cmdFile.nativePath,
> 	"-Dfile.encoding=UTF8",
> 	"-Droyalelib=" + frameworksPath,
> 	"-cp",
> 	cp,
> 	"moonshine.Main"
> ];
> ```
> 
> After:
> 
> ```actionscript-3
> var languageServerCommand:Vector.<String> = new <String>[
> 	cmdFile.nativePath,
> 	"-Xmx2g",
> 	"-Dfile.encoding=UTF8",
> 	"-Droyalelib=" + frameworksPath,
> 	"-cp",
> 	cp,
> 	"moonshine.Main"
> ];
> ```
> 
> As I understand it, the `2g` part of `-Xmx2g` means 2 GB of RAM. You could try increasing it higher, if 2g doesn't work. I don't know for sure if it's an out of memory issue, though, so there's no guarantee that this will help.
> 
> If it works, we can add a new setting to Moonshine to increase the memory used by the language server(s).
> 
> 2. In the same file, in the `initializeLanguageServer()` method, set `debugMode` to `true`, which will print the messages between Moonshine and the language server to the debug console. Once the error starts happening, there might be a clue in that output. You can copy/paste it here and I'll take a look.

Josh unfortunately I cannot do this. I'm working on client's corporate machine. I cannot copy there any files, I'm not able clone Moonshine repository etc. If I do above changes on master, I got next development build ready - would it be sufficient ? I can also setup development build to debug mode (swf file build with debug=true) - In fact I'm thinking about having development build in debug mode for a long time. Maybe only released version should have that debug=false.

**Comment by piotrzarzycki21** [comment]
Ignore my comment - I just found a way to clone repository there and see if I can run thins from IDE.

**Comment by piotrzarzycki21** [comment]
It looks like I won't be able setup on that machine IDE - Too many things is being blocked and all. The only proposition from my sight is to do changes on master.

**Comment by piotrzarzycki21** [comment]
> You get the message only. In those cases, there's probably an event like `IOErrorEvent.IO_ERROR` that we might be able to use to get more info.

Where that event should be registered ?

**Comment by joshtynjala** [comment]
> I was thinking right now why we do not get any details for it. If "swf" of Moonshine is being build with debug=true - maybe this error happens from swc which is being build with debug=false and it doesn't provide us any info - What do you think ?

I believe that a stack trace would still be available, even in that case. All function names are known at runtime because AS3 supports dynamic access like `obj["funcName"]()`, so there isn't any information missing that would prevent it from giving us the full stack trace. I think that it's like I said: "There is no stack trace because the exception doesn't originate from an ActionScript function." The exception originates somewhere inside the runtime. The runtime has various background threads for networking and things, and an exception is probably being thrown asynchronously.

> Where that event should be registered ?
> Should we add there ?
_languageServerProcess.addEventListener(IOErrorEvent.STANDARD_ERROR_IO_ERROR, languageServerProcess_standardErrorIOError);

Yes, since the exception is "3218 | Error while writing data to NativeProcess.standardInput.", listening for an event on the native process may be how we catch it. Based on the error message, I suspect that it is `IOErrorEvent.STANDARD_INPUT_IO_ERROR` rather than `IOErrorEvent.STANDARD_ERROR_IO_ERROR`.

**Comment by joshtynjala** [comment]
> n the same file, in the initializeLanguageServer() method, set debugMode to true, which will print the messages between Moonshine and the language server to the debug console.

> Non of this helps to neither fix or get more details of this error.

Can you post the full output from your IDE's debug console? I might be able to figure out more details from this output.

**Comment by joshtynjala** [comment]
Oh wait, you said that you couldn't run Moonshine from an IDE. Well, unfortunately, setting `debugMode` won't help you in this situation. It prints to the IDE's debug console. It does not print to any view that you can access from inside Moonshine.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I'm not sure if this is related to your changes here https://github.com/Moonshine-IDE/Moonshine-IDE/commit/c2573a6126f3ed5829f4428e02dd4922a237b1c6 or this error 3218 started to manifest itself with more data. Right now this error is being shown in console  and hang Moonshine. Let me know if you need separate issue. 

```
: Cannot open branch because it is not in the data provider.
: ArgumentError: Cannot open branch because it is not in the data provider.
: 	at feathers.controls::TreeView/toggleBranch()
: 	at moonshine.plugin.problems.view::ProblemsView/problemsView_problems_replaceItemHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at moonshine.plugin.problems.data::DiagnosticHierarchicalCollection/setDiagnostics()
: 	at actionScripts.plugin.problems::ProblemsPlugin/handleShowDiagnostics()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.languageServer::ActionScriptLanguageServerManager/languageClient_publishDiagnosticsHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at moonshine.lsp::LanguageClient/textDocument__publishDiagnostics()
: 	at moonshine.lsp::LanguageClient/parseNotificationMessage()
: 	at moonshine.lsp::LanguageClient/parseMessage()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/parseMessageBuffer()
: 	at moonshine.lsp::LanguageClient/languageClient_input_onData()
```

**Comment by piotrzarzycki21** [comment]
@joshtynjala I was able reproduce that error on my private Windows machine. I have there Flex project from one client and when I open one of the file mxml or as I'm getting following:

`Error #2044: Unhandled IOErrorEvent:. text=Error #3218 Error while writing data to NativeProcess.standardInput`

**Comment by piotrzarzycki21** [comment]
When I register to "IOErrorEvent.STANDARD_INPUT_IO_ERROR" I catch above error, but there is not much more than I posted above. Here is what I'm getting in IDE console:

```
 SAVE ADMIN CHANGE ORG DESCRIPTION ******************************/\n\t\t\n\t\tpublic function dpSaveAdminOrgDesc(... params:Array):void {\n\t\t\t_remoteObject.SaveAdminOrgDesc.addEventListener(ResultEvent.RESULT,onSaveAdminOrgDescResult);\n\t\t\t_remoteObject.SaveAdminOrgDesc.addEventListener(FaultEvent.FAULT,onSaveAdminOrgDescFault);\n\t\t\tvar bl:Operation=_remoteObject.SaveAdminOrgDesc;\n\t\t\tbl.send.apply(this,params);\n\t\t}\n\t\t\n\t\tprivate function onSaveAdminOrgDescResult(event:ResultEvent):void {\n\t\t\tvar e:MyDataEvent=new MyDataEvent(EVENT_RESULT);\n\t\t\t_remoteObject.SaveAdminOrgDesc.removeEventListener(ResultEvent.RESULT,onSaveAdminOrgDescResult);\n\t\t\t_remoteObject.SaveAdminOrgDesc.removeEventListener(FaultEvent.FAULT,onSaveAdminOrgDescFault);\n\t\t\te.data=event.result;\n\t\t\te.dataProxy=this;\n\t\t\tthis.dispatchEvent(e);\n\t\t}\n\t\t\n\t\tprivate function onSaveAdminOrgDescFault(event:FaultEvent):void {\n\t\t\tvar e:MyDataEvent=new MyDataEvent(EVENT_FAULT);\n\t\t\t_remoteObject.SaveAdminOrgDesc.removeEventListener(ResultEvent.RESULT,onSaveAdminOrgDescResult);\n\t\t\t_remoteObject.SaveAdminOrgDesc.removeEventListener(FaultEvent.FAULT,onSaveAdminOrgDescFault);\n\t\t\te.dataProxy=this;\n\t\t\te.description=event.fault.faultString + \" : \" + event.fault.faultDetail + \" (onSaveAdminOrgDescFault)\";\n\t\t\tthis.dispatchEvent(e);\n\t\t}\n\t\t\n\t\t\n\t\t/****************************** GET ADMIN LOG TAB DATA ******************************/\n\t\t\n\t\tpublic function dpGetAdminLogTabData(... params:Array):void {\n\t\t\t_remoteObject.GetAdminLogTabData.addEventListener(ResultEvent.RESULT,onGetAdminLogTabDataResult);\n\t\t\t_remoteObject.GetAdminLogTabData.addEventListener(FaultEvent.FAULT,onGetAdminLogTabDataFault);\n\t\t\tvar gcs:Operation=_remoteObject.GetAdminLogTabData;\n\t\t\tgcs.send.apply(this,params);\n\t\t}\n\t\t\n\t\tprivate function onGetAdminLogTabDataResult(event:ResultEvent):void {\n\t\t\tvar e:MyDataEvent=
[trace] "
[trace] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
[trace] 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
[trace] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[trace] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[trace] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[trace] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[trace] 	at java.base/java.lang.Thread.run(Thread.java:834)
[trace] Jun 13, 2022 11:50:29 AM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
[trace] SEVERE: Missing header Content-Length in input "{"id":53,"params":{"range":{"start":{"character":7,"line":90},"end":{"character":7,"line":90}},"textDocument":{"uri":"file:///D:/Work/projects/Sitime/air-apps/main-app/src/com/jitterTime/data/DataProxy.as"},"context":{"diagnostics":[]}},"method":"textDocument/codeAction","jsonrpc":"2.0"}Content-Length: 288
[trace] "
[trace] java.lang.IllegalStateException: Missing header Content-Length in input "{"id":53,"params":{"range":{"start":{"character":7,"line":90},"end":{"character":7,"line":90}},"textDocument":{"uri":"file:///D:/Work/projects/Sitime/air-apps/main-app/src/com/jitterTime/data/DataProxy.as"},"context":{"diagnostics":[]}},"method":"textDocument/codeAction","jsonrpc":"2.0"}Content-Length: 288
[trace] "
[trace] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
[trace] 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
[trace] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[trace] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[trace] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[trace] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[trace] 	at java.base/java.lang.Thread.run(Thread.java:834)
[trace] IOErrorEvent Error #3218: Error while writing data to NativeProcess.standardInput.
[trace] IOErrorEvent Error #3218: Error while writing data to NativeProcess.standardInput.
[trace] IOErrorEvent Error #3218: Error while writing data to NativeProcess.standardInput.
[trace] IOErrorEvent Error #3218: Error while writing data to NativeProcess.standardInput.
[trace] IOErrorEvent Error #3218: Error while writing data to NativeProcess.standardInput.
[trace] IOErrorEvent Error #3218: Error while writing data to NativeProcess.standardInput.
```

**Comment by joshtynjala** [comment]
> SEVERE: Missing header Content-Length in input "{"id":53,"params":{"range":{"start":{"character":7,"line":90},"end":{"character":7,"line":90}},"textDocument":{"uri":"file:///D:/Work/projects/Sitime/air-apps/main-app/src/com/jitterTime/data/DataProxy.as"},"context":{"diagnostics":[]}},"method":"textDocument/codeAction","jsonrpc":"2.0"}Content-Length: 288

This is some interesting output. It indicates to me that some Language Server Protocol messages sent by Moonshine may be malformed.

**Comment by piotrzarzycki21** [comment]
The question is whether it is enough to fix that. I may ask this particular client whether I can get of one specific file with code to show you if it helps?

**Comment by joshtynjala** [comment]
It might help. You can send it privately to my email, if they prefer it.

**Comment by joshtynjala** [comment]
Commenting to link to a past issue about the same error: Moonshine-IDE/Moonshine-IDE#492

**Comment by joshtynjala** [comment]
Committed Moonshine-IDE/moonshine-openfl-language-client@75d59dbdbd266b9e0c4ea1d4f3e505a6a07a9474, which may help with this issue. While my previous attempts to fix this resulted in some messages being sent to the language server in "chunks", I discovered that some other types of messages were being sent all at once, even if they were large. Now, all messages sent to the language server should be chunked.

**Comment by joshtynjala** [comment]
(To use commit Moonshine-IDE/moonshine-openfl-language-client@75d59dbdbd266b9e0c4ea1d4f3e505a6a07a9474, MoonshineGUICore must be rebuilt).

**Comment by piotrzarzycki21** [comment]
> I just found that I can reproduce Error 3218 issue consistently on Windows. Steps:
> 
> 1. Open a **Flex** project in Moonshine.
> 2. Go to Edit -> Open Symbol in Project
> 3. Open `UIComponent`
> 
> I cannot reproduce the same issue on macOS.

Same here. I have never reproduce this issue on MacOs which is right now my main OS for daily usage.

**Comment by rat-moonshine** [comment]
> > (To use commit [Moonshine-IDE/moonshine-openfl-language-client@75d59db](https://github.com/Moonshine-IDE/moonshine-openfl-language-client/commit/75d59dbdbd266b9e0c4ea1d4f3e505a6a07a9474), MoonshineGUICore must be rebuilt).
> 
> @rat-moonshine Does MoonshineGUICore is rebuild every time on bamboo build ?

Yes.

**Comment by joshtynjala** [comment]
> Ok but how does it actually work? If I rebuild MoonshineGUICore does it automatically take changes from [moonshine-openfl-language-client@75d59db](https://github.com/Moonshine-IDE/moonshine-openfl-language-client/commit/75d59dbdbd266b9e0c4ea1d4f3e505a6a07a9474) ?

You need to pull changes to moonshine-openfl-language-client, and then build MoonshineGUICore. If you used `haxelib git [...]` to install moonshine-openfl-language-client, you can run `haxelib update moonshine-openfl-language-client`, and it will pull. If you manually checked out the repo with git and used `haxelib dev [...]` to set it as the development version, you need to manually `git pull origin master`.

**Comment by joshtynjala** [comment]
I've been experimenting for a number of hours today, but I can't seem to find a workaround for Error 3218 yet. A few things that I've tried:

1) Writing a small number of bytes at a time (such as 512, which should be far below any limit). Then, waiting until the `bytesLoaded` value of `ProgressEvent.STANDARD_INPUT_PROGRESS` dispatched by the `NativeProcess` matches the number of bytes written before writing any more. This should rule out the possibility that AIR might have some kind of internal buffer that's too small. 
2) After waiting for `ProgressEvent.STANDARD_INPUT_PROGRESS`, similar to above, introduce an additional small delay (with `setTimeout()` or `Event.ENTER_FRAME`) before writing more data. If the delay is large enough, this will actually work, but that large delay is in the hundreds of milliseconds — which is _way_ too long to make this a feasible workaround.
3) Instead of using `EnvironmentSetupUtils.getInstance().initCommandGenerationToSetLocalEnvironment()` to launch the language server using cmd.exe, run the language server directly with `NativeProcess` instead. This rules out the possibility that this error is caused by cmd.exe acting as mediator.

I may try to switch to using a socket instead of stdout/stdin. That's how I originally launched the AS3/MXML language server, when I first introduced it to Moonshine. I eventually switched to stdin/stdout due to performance issues with the socket approach.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 I just pushed the changes to make the AS3 & MXML language server use a socket instead of stdio. Let me know if it helps!
